version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "5500:80"
    depends_on:
      - backend
